# Generated by Django 5.0.6 on 2024-10-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='author_email',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='content',
        ),
    ]
