# Generated by Django 5.0.6 on 2024-10-01 17:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_email_comment_author_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
